apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: order-service-build
  namespace: my-app-prod
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/my-org/order-service.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: order-service:latest
  triggers:
    - type: ConfigChange
    - type: ImageChange