apiVersion: v1
kind: ServiceAccount
metadata:
  name: order-service-sa
  namespace: my-app-prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: order-service-scc-binding
  namespace: my-app-prod
subjects:
  - kind: ServiceAccount
    name: order-service-sa
    namespace: my-app-prod
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:restricted-v2
  apiGroup: rbac.authorization.k8s.io